name: dashboard_ipi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  get: ^4.6.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    
  fonts:
    - family: KANITBOLD
      fonts:
        - asset: assets/fonts/Kanit-Bold.ttf

    - family: LEMONMILK
      fonts:
        - asset: assets/fonts/LEMONMILK-Regular.otf

    - family: LEMONMILK-BOLD
      fonts:
        - asset: assets/fonts/LEMONMILK-Bold.otf
    
    - family: ROBOTOCONDENSED
      fonts:
        - asset: assets/fonts/RobotoCondensed.ttf
