// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaCVigzwVRuDy6pU6lrfex6gyAY8Tg9BM',
    appId: '1:1035260998061:android:bd2c8a6cd6d95e230b7124',
    messagingSenderId: '1035260998061',
    projectId: 'event-form-fb9eb',
    databaseURL: 'https://event-form-fb9eb-default-rtdb.firebaseio.com',
    storageBucket: 'event-form-fb9eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGbgbLSrJQXv2Chgr60wRx_ooUZ3S_EJg',
    appId: '1:1035260998061:ios:cedd058051bfda6f0b7124',
    messagingSenderId: '1035260998061',
    projectId: 'event-form-fb9eb',
    databaseURL: 'https://event-form-fb9eb-default-rtdb.firebaseio.com',
    storageBucket: 'event-form-fb9eb.firebasestorage.app',
    iosBundleId: 'com.teste.dashboardIpi',
  );

}